import React from 'react';
import {motion} from 'framer-motion';
import {DecisionOutcome,RiskEvaluationResult,PolicyEvaluationResult} from '../services/iamApi';
import {Activity,GitBranch,ShieldAlert,CheckCircle2} from 'lucide-react';

export const DecisionFlow:React.FC<{risk:RiskEvaluationResult|null;policy:PolicyEvaluationResult|null;decision:DecisionOutcome|null}>=({risk,policy,decision})=>{
 const violations=policy?.violations??[]; const stages=[['Identity context',!!risk,Activity],['Risk evaluation',!!risk,GitBranch],['Policy check',violations.length>0||!!policy,ShieldAlert],['Decision',!!decision,CheckCircle2]];
 return <div className="rounded-xl border border-white/[0.08] bg-[#0b0c0f] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[10px] uppercase tracking-[.14em] text-white/25">Decision pipeline</div><h3 className="mt-1 text-[14px] font-medium">Identity → risk → policy → action</h3><p className="mt-1 text-[11px] text-white/28">The same evaluation chain used to produce the selected decision.</p></div><div className="text-right"><div className="font-mono text-2xl font-semibold">{risk?.riskScore??'—'}<span className="text-[10px] font-normal text-white/25"> / 100</span></div><div className="text-[9px] uppercase tracking-[.12em] text-white/20">risk score</div></div></div>
 <div className="mt-8 grid gap-2 sm:grid-cols-4">{stages.map(([label,active,Icon],i)=><div key={String(label)} className="relative"><div className="flex items-center gap-3 rounded-lg border border-white/[0.07] bg-white/[0.02] p-3"><motion.div initial={{scale:.94,opacity:.6}} animate={{scale:active?1:0.96,opacity:active?1:.45}} className={'grid h-8 w-8 shrink-0 place-items-center rounded-md border '+(active?'border-white/15 bg-white/[0.07] text-white':'border-white/5 text-white/25')}><Icon className="h-3.5 w-3.5"/></motion.div><div><div className="text-[11px] font-medium text-white/60">{String(label)}</div><div className="mt-1 text-[9px] text-white/22">{active?'evaluated':'waiting'}</div></div></div>{i<3&&<div className="hidden sm:block absolute -right-1.5 top-1/2 h-px w-3 bg-white/10"/>}</div>)}</div>
 {decision&&<div className="mt-4 flex items-center justify-between rounded-lg border border-white/[0.07] bg-white/[0.02] px-4 py-3"><span className="text-[11px] text-white/35">Final decision</span><span className="rounded-md border border-white/10 px-2.5 py-1 text-[10px] uppercase tracking-wide text-white/65">{decision.replaceAll('_',' ')}</span></div>}
 </div>;
};